package:
  name: "genial"
  version: "1.0.17"

source:
  path: /media/DATA/PAULINE/ABRicate/GENIAL/

requirements:
  host:
    - python
    - setuptools
    - git

  run:
    - biopython=1.72
    - pandas=0.23.4
    - python>=3.0
    - seaborn=0.9.0
    - abricate=0.8.7
    - xlrd>=0.9.0
    - pymongo

about:
  home: https://github.com/p-barbet/GENIAL
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  license_file: LICENSE
  summary: GENIAL - GENes Indentification with Abricate for Lucky biologists
